// Pre-computed demo data for display when no DB data exists
export const demoUsers = [
  {
    id: "USR001",
    fullName: "Aarav Kulkarni",
    employmentType: "Student",
    creditScore: 724,
    riskLevel: "Medium" as const,
    fraudStatus: "Clear" as const,
    fraudRiskPercentage: 15,
    loanEligibilityAmount: 160000,
    monthlyIncome: 12000,
    averageMonthlyCashFlow: 6800,
    minimumBalanceMaintained: 9500,
    repaymentConsistency: 90,
    loanDecision: { status: "Approved" as const, approvedAmount: 140000, interestRate: 11, tenureMonths: 24, emiAmount: 6200, reason: "Stable guardian income and consistent repayment" },
    transactions: [
      { date: "2025-01-01", category: "College Fees", description: "Semester Fees", type: "Debit", amount: 18000 },
      { date: "2025-01-03", category: "Food", description: "Swiggy", type: "Debit", amount: 1200 },
      { date: "2025-01-05", category: "Rent", description: "PG Rent", type: "Debit", amount: 8500 },
      { date: "2025-01-07", category: "UPI Transfer", description: "Friend Transfer", type: "Credit", amount: 3000 },
      { date: "2025-01-08", category: "Utilities", description: "Electricity Bill", type: "Debit", amount: 1500 },
      { date: "2025-01-10", category: "Transport", description: "Metro Recharge", type: "Debit", amount: 800 },
      { date: "2025-01-12", category: "Hospital", description: "Clinic Visit", type: "Debit", amount: 2200 },
      { date: "2025-01-15", category: "Course Fee", description: "Online Certification", type: "Debit", amount: 5000 },
      { date: "2025-01-18", category: "UPI Transfer", description: "Received from Parent", type: "Credit", amount: 10000 },
      { date: "2025-01-20", category: "Food", description: "Groceries", type: "Debit", amount: 3000 },
      { date: "2025-01-22", category: "Loan Repayment", description: "EMI Payment", type: "Debit", amount: 3500 },
      { date: "2025-01-24", category: "Transport", description: "Fuel", type: "Debit", amount: 2000 },
      { date: "2025-01-26", category: "UPI Transfer", description: "Friend Return", type: "Debit", amount: 1500 },
      { date: "2025-01-28", category: "Food", description: "Restaurant", type: "Debit", amount: 2200 },
      { date: "2025-01-30", category: "Utilities", description: "Internet Bill", type: "Debit", amount: 1000 },
    ],
    transparency: {
      positiveFactors: ["Consistent EMI payments on time", "Guardian income stability (₹65,000/mo)", "Regular utility bill payments"],
      negativeFactors: ["Low personal income (₹12,000)", "High college fee burden", "Occasional high food expenses"],
      suggestions: ["Maintain minimum balance above ₹10,000", "Reduce dining-out expenses by 20%", "Build emergency fund of 3 months expenses"],
      featureImportance: { "Income Stability": 0.28, "Expense Discipline": 0.22, "Repayment History": 0.25, "Balance Maintenance": 0.15, "Fraud Risk": 0.10 },
    },
    fraudDetails: { patterns: [] },
  },
  {
    id: "USR002",
    fullName: "Riya Mehta",
    employmentType: "Working Professional",
    creditScore: 792,
    riskLevel: "Low" as const,
    fraudStatus: "Clear" as const,
    fraudRiskPercentage: 7,
    loanEligibilityAmount: 400000,
    monthlyIncome: 55000,
    averageMonthlyCashFlow: 32000,
    minimumBalanceMaintained: 30000,
    repaymentConsistency: 97,
    loanDecision: { status: "Approved" as const, approvedAmount: 350000, interestRate: 9, tenureMonths: 36, emiAmount: 11200, reason: "High credit score and stable salary" },
    transactions: [
      { date: "2025-01-01", category: "Salary", description: "Monthly Salary", type: "Credit", amount: 55000 },
      { date: "2025-01-02", category: "Rent", description: "Apartment Rent", type: "Debit", amount: 20000 },
      { date: "2025-01-04", category: "Utilities", description: "Electricity Bill", type: "Debit", amount: 3500 },
      { date: "2025-01-06", category: "Food", description: "Groceries", type: "Debit", amount: 6000 },
      { date: "2025-01-08", category: "Transport", description: "Fuel", type: "Debit", amount: 4000 },
      { date: "2025-01-10", category: "Hospital", description: "Health Checkup", type: "Debit", amount: 2500 },
      { date: "2025-01-12", category: "UPI Transfer", description: "Friend Payment", type: "Debit", amount: 3000 },
      { date: "2025-01-15", category: "UPI Transfer", description: "Received Refund", type: "Credit", amount: 2000 },
      { date: "2025-01-18", category: "Food", description: "Dining", type: "Debit", amount: 4500 },
      { date: "2025-01-20", category: "Utilities", description: "Internet Bill", type: "Debit", amount: 1500 },
      { date: "2025-01-22", category: "Transport", description: "Uber", type: "Debit", amount: 1800 },
      { date: "2025-01-25", category: "Food", description: "Swiggy", type: "Debit", amount: 2300 },
      { date: "2025-01-27", category: "UPI Transfer", description: "Family Transfer", type: "Credit", amount: 5000 },
      { date: "2025-01-28", category: "Utilities", description: "Water Bill", type: "Debit", amount: 900 },
      { date: "2025-01-30", category: "Food", description: "Groceries", type: "Debit", amount: 3500 },
    ],
    transparency: {
      positiveFactors: ["Stable monthly salary of ₹55,000", "97% repayment consistency", "High minimum balance (₹30,000)"],
      negativeFactors: ["High rent-to-income ratio (36%)", "Multiple dining expenses", "Occasional UPI transfers"],
      suggestions: ["Consider reducing rent to below 30% of income", "Set up auto-pay for all bills", "Increase savings by 10%"],
      featureImportance: { "Income Stability": 0.32, "Expense Discipline": 0.20, "Repayment History": 0.28, "Balance Maintenance": 0.12, "Fraud Risk": 0.08 },
    },
    fraudDetails: { patterns: [] },
  },
  {
    id: "USR003",
    fullName: "Karan Verma",
    employmentType: "Student",
    creditScore: 585,
    riskLevel: "High" as const,
    fraudStatus: "Suspicious" as const,
    fraudRiskPercentage: 76,
    loanEligibilityAmount: 50000,
    monthlyIncome: 10000,
    averageMonthlyCashFlow: 2500,
    minimumBalanceMaintained: 3000,
    repaymentConsistency: 58,
    loanDecision: { status: "Rejected" as const, approvedAmount: 0, interestRate: 0, tenureMonths: 0, emiAmount: 0, reason: "High fraud risk and irregular repayment" },
    transactions: [
      { date: "2025-01-02", category: "UPI Transfer", description: "Transfer A", type: "Debit", amount: 10000 },
      { date: "2025-01-02", category: "UPI Transfer", description: "Transfer B", type: "Credit", amount: 10000 },
      { date: "2025-01-03", category: "UPI Transfer", description: "Transfer A", type: "Debit", amount: 10000 },
      { date: "2025-01-03", category: "UPI Transfer", description: "Transfer B", type: "Credit", amount: 10000 },
      { date: "2025-01-04", category: "UPI Transfer", description: "Transfer A", type: "Debit", amount: 10000 },
      { date: "2025-01-05", category: "Food", description: "Groceries", type: "Debit", amount: 2000 },
      { date: "2025-01-07", category: "College Fees", description: "Exam Fee", type: "Debit", amount: 5000 },
      { date: "2025-01-09", category: "Hospital", description: "Medical Expense", type: "Debit", amount: 1800 },
      { date: "2025-01-11", category: "Rent", description: "Hostel Fee", type: "Debit", amount: 6000 },
      { date: "2025-01-14", category: "Loan Repayment", description: "EMI Payment", type: "Debit", amount: 4000 },
    ],
    transparency: {
      positiveFactors: ["Some EMI payments made", "College fee payments on record", "Basic utilities paid"],
      negativeFactors: ["Circular UPI transfers detected (5+)", "Very low minimum balance (₹3,000)", "Irregular income pattern"],
      suggestions: ["Stop circular transactions immediately", "Maintain minimum balance above ₹5,000", "Ensure consistent monthly income"],
      featureImportance: { "Income Stability": 0.15, "Expense Discipline": 0.12, "Repayment History": 0.18, "Balance Maintenance": 0.10, "Fraud Risk": 0.45 },
    },
    fraudDetails: {
      patterns: [
        "5 circular UPI transfers detected between linked accounts (₹10,000 each)",
        "Repeated same-day debit-credit pattern flagged",
        "Unusual transaction frequency: 5 transfers in 3 days",
        "Income mismatch: declared ₹10,000 but ₹50,000 in circular transfers"
      ],
    },
  },
];

// Currently selected user for demo purposes
export const getCurrentDemoUser = () => demoUsers[0];

export const CATEGORY_COLORS: Record<string, string> = {
  "Rent": "hsl(var(--chart-1))",
  "Food": "hsl(var(--chart-2))",
  "College Fees": "hsl(var(--chart-3))",
  "Hospital": "hsl(var(--chart-5))",
  "Course Fee": "hsl(var(--chart-4))",
  "Utilities": "hsl(180 60% 50%)",
  "Transport": "hsl(200 70% 50%)",
  "UPI Transfer": "hsl(260 60% 55%)",
  "Loan Repayment": "hsl(330 70% 50%)",
  "Salary": "hsl(var(--chart-2))",
};
